### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by ileonemil** [5pecia1/n8n-workflow#1]
Hi, i get this error:
`WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
4aeca02ede887fd52625ff6c5ea91380176137b77a4e41a995cb7189c1250f2e
docker: Error response from daemon: Mounts denied: 
The path /n8n is not shared from the host and is not known to Docker.
You can configure shared paths from Docker -> Preferences... -> Resources -> File Sharing.
See https://docs.docker.com/docker-for-mac for more info.`

**Comment by 5pecia1** [comment]
Hi!.
Are you using Raspberry Pi or another arm architecture CPU?
Sorry, the docker image do not support arm architecture CPUs.
If you are not using arm CPU, You need to update your docker version.(https://github.com/dani-garcia/vaultwarden/discussions/1264#discussioncomment-206773)
