### ISSUE TITLE
no page / event is made

### ISSUE THREAD

**Issue by shirobachi** [5pecia1/n8n-workflow#2]
Hey, 

Thanks for that workflow, it's cool! 
I set all staff what wrote in README and run this workflow all staff work properly just action maker give always empty tables
![image](https://user-images.githubusercontent.com/16509749/129263375-9977378f-51a0-41d5-9a46-cb772e9bea00.png)

can I ask for assist?

**Comment by 5pecia1** [comment]
Thanks your feedback!
Should I show Merge result as text?
any part is good.

**Comment by shirobachi** [comment]
Sure, but output is complicated to read (at least for me), it will expire in 3 days
https://paste.gg/p/Shirobachi/cd8c7e4115714f769b6e2399182cca07

Also, when I edited notion page and run workflow I got this
![image](https://user-images.githubusercontent.com/16509749/129539017-b8e00456-9a62-444e-aa4a-b300ca2c64bc.png)


Thanks 4 your time and help!
