### ISSUE TITLE
New n8n features

### ISSUE THREAD

**Issue by salomaoparkour** [5pecia1/n8n-workflow#3]
After many updates to n8n, I've been trying to create a similar solution.
They have released better triggers for GCal and also have improved Notion nodes considerably.

I'm using a property called GCal ID as a relation between items in the calendar and Notion.
And I also decided to always keep the original page in Notion. And change the Calendar instead.

But I'm facing some issues when updating the events. Are you still interested in creating this solution?

This is the JSON code for the flow I'm trying to build. Just copy and paste in n8n.

`{
  "meta": {
    "instanceId": "f9c40bccfbfb973b8ba2bfd7b70b906c2376bb9900216d1ce424582c3097fb66"
  },
  "nodes": [
    {
      "parameters": {
        "calendar": {
          "__rl": true,
          "value": "728c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "start": "={{ $json.properties.Data.date.start}}",
        "end": "={{ $json.properties.Data.date.end === null\n   ? $json.properties.Data.date.start\n   : $json.properties.Data.date.end }}",
        "additionalFields": {
          "allday": "={{ $json.properties.Data.date.end === null\n   ? \"yes\"\n   : \"no\" }}",
          "summary": "={{ $json.properties['Task name'].title[0].text.content }}"
        }
      },
      "id": "a91929a4-3178-48ed-99c5-8d6f4a807dc2",
      "name": "Google Calendar1",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        1640,
        660
      ],
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $('Notion').item.json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text",
              "textContent": "={{ $json.id }}"
            }
          ]
        },
        "options": {}
      },
      "id": "823772fd-005d-47f8-bc11-56404287a8d6",
      "name": "Add GCal ID",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1800,
        660
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {},
      "id": "8a309bf8-8ac5-442c-8f28-3604052bdce1",
      "name": "No Operation, do nothing",
      "type": "n8n-nodes-base.noOp",
      "typeVersion": 1,
      "position": [
        1360,
        740
      ]
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $('Notion').item.json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text"
            }
          ]
        },
        "options": {}
      },
      "id": "256eabaf-e7e4-47f4-bd29-2ad8f34f6c96",
      "name": "Remove GCal ID1",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1560,
        -540
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "content": "# Create event",
        "height": 80,
        "width": 288.259119644621
      },
      "id": "c3115c37-014e-4c6f-8b99-56f0efa336cb",
      "name": "Sticky Note",
      "type": "n8n-nodes-base.stickyNote",
      "typeVersion": 1,
      "position": [
        1120,
        500
      ]
    },
    {
      "parameters": {
        "content": "# Update Event",
        "height": 80,
        "width": 299.54925745153224
      },
      "id": "3c598037-fcef-4a53-bd67-a458b4db5207",
      "name": "Sticky Note1",
      "type": "n8n-nodes-base.stickyNote",
      "typeVersion": 1,
      "position": [
        1100,
        160
      ]
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $('Notion').item.json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text"
            }
          ]
        },
        "options": {}
      },
      "id": "a83b0e02-d215-42c7-9cf0-a7bf941fd65a",
      "name": "Remove GCal ID2",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1920,
        160
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "calendar": {
          "__rl": true,
          "value": "72fb8c8cca38c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "start": "={{ $('Event exists in GCal?').item.json[\"properties\"][\"Data\"][\"date\"][\"start\"] }}",
        "end": "={{ $json.properties.Data.date.end === null\n   ? $json.properties.Data.date.start\n   : $json.properties.Data.date.end }}",
        "additionalFields": {
          "allday": "={{ $json.properties.Data.date.end === null\n   ? \"yes\"\n   : \"no\" }}",
          "summary": "={{ $json.properties['Task name'].title[0].text.content }}"
        }
      },
      "id": "24d78bb4-41ea-4988-8422-99feb595552a",
      "name": "Google Calendar2",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        2140,
        -120
      ],
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $('Notion').item.json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text",
              "textContent": "={{ $json.id }}"
            }
          ]
        },
        "options": {}
      },
      "id": "f2f2b0fb-02c5-4a2e-be7e-b15948676d11",
      "name": "Add GCal ID2",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        2360,
        -120
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $('Notion').item.json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text"
            }
          ]
        },
        "options": {}
      },
      "id": "970846ce-ef5f-438a-8f42-4d5dcbb14467",
      "name": "Remove GCal ID",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1920,
        -120
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "calendar": {
          "__rl": true,
          "value": "72fb85b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "start": "={{ $json.properties.Data.date.start}}",
        "end": "={{ /*Checks if it has an endDate and time*/\n\n$if($json.properties.Data.date.end === null,\n    $json.properties.Data.date.start.plus({hours: 7}),\n    $json.properties.Data.date.end\n)\n}}",
        "additionalFields": {
          "summary": "={{ $json.properties['Task name'].title[0].text.content }}"
        }
      },
      "id": "302eb25c-5e6c-46e6-941a-a8c09a678fb3",
      "name": "Google Calendar",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        1640,
        500
      ],
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $('Notion').item.json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text",
              "textContent": "={{ $json.id }}"
            }
          ]
        },
        "options": {}
      },
      "id": "bdbeb0a6-78e1-42cc-80e8-0a720ba60d77",
      "name": "Add GCal ID1",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1800,
        500
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "content": "## Deletes GCal ID and Date, when the event is cancelled in GCal.",
        "height": 95.34469942625078,
        "width": 484.39703616877216
      },
      "id": "f527b201-d97b-4307-8fdc-1deb32b25678",
      "name": "Sticky Note2",
      "type": "n8n-nodes-base.stickyNote",
      "typeVersion": 1,
      "position": [
        760,
        1320
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        },
        "event": "pagedUpdatedInDatabase",
        "databaseId": {
          "__rl": true,
          "value": "dad4835c-1acc-4209-aac2-11440b13c475",
          "mode": "list",
          "cachedResultName": "Tasks",
          "cachedResultUrl": "https://www.notion.so/dad40b13c475"
        },
        "simple": false
      },
      "id": "6d70adb7-d9f9-4941-b909-a9b7557a2a52",
      "name": "Notion",
      "type": "n8n-nodes-base.notionTrigger",
      "typeVersion": 1,
      "position": [
        760,
        300
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        },
        "calendarId": {
          "__rl": true,
          "value": "72fb857a38c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "triggerOn": "eventUpdated",
        "options": {}
      },
      "id": "98190564-8f9b-42e1-a96f-cba7445d7f99",
      "name": "Event updated",
      "type": "n8n-nodes-base.googleCalendarTrigger",
      "typeVersion": 1,
      "position": [
        760,
        1800
      ],
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "content": "## Updates event date in Notion",
        "height": 94.398709492026,
        "width": 504.7480652643237
      },
      "id": "408808df-cb00-482f-8118-5319015495e2",
      "name": "Sticky Note3",
      "type": "n8n-nodes-base.stickyNote",
      "typeVersion": 1,
      "position": [
        760,
        1680
      ]
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.properties['GCal ID'].rich_text[0].text.content }}",
              "operation": "isNotEmpty"
            }
          ]
        }
      },
      "id": "767813f8-6def-4f64-86b8-eceb97a3b5e0",
      "name": "Event exists in GCal?",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        960,
        300
      ]
    },
    {
      "parameters": {
        "conditions": {
          "boolean": [
            {
              "value1": "={{ $json.archived }}",
              "value2": "={{ true }}"
            }
          ]
        }
      },
      "id": "69d357ff-9330-4e6d-a39a-93ccc2b31ee3",
      "name": "Has it been deleted?",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1140,
        -20
      ]
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.properties.Data.date }}",
              "operation": "isNotEmpty"
            }
          ]
        }
      },
      "id": "283b30f3-a177-471f-9540-ae4ea61910ac",
      "name": "Does it have a date?",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1320,
        0
      ]
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.properties.Data.date.start }}",
              "operation": "contains",
              "value2": "T"
            }
          ]
        }
      },
      "id": "020ddeee-884c-49d2-8d36-f58f5fed09a7",
      "name": "Does it have a time?",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1520,
        -140
      ]
    },
    {
      "parameters": {
        "operation": "delete",
        "calendar": {
          "__rl": true,
          "value": "72fb85cca38c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "eventId": "={{ $json.properties['GCal ID'].rich_text[0].text.content }}",
        "options": {}
      },
      "id": "3c3222eb-91ee-4fbc-be57-10d0944a232d",
      "name": "Delete event",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        1360,
        -540
      ],
      "alwaysOutputData": false,
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "operation": "update",
        "calendar": {
          "__rl": true,
          "value": "72fb857fe78a9c8cca38c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "eventId": "={{ $json.properties['GCal ID'].rich_text[0].text.content }}",
        "updateFields": {
          "allday": "={{ $json.properties.Data.date.end === null\n   ? \"yes\"\n   : \"no\" }}",
          "end": "={{ $json.properties.Data.date.end === null\n   ? $json.properties.Data.date.start\n   : $json.properties.Data.date.end }}",
          "start": "={{ $json.properties.Data.date.start }}",
          "summary": "={{ $json.properties['Task name'].title[0].text.content }}"
        }
      },
      "id": "c41c88b3-7545-4469-99bb-d4b789981c1c",
      "name": "Update event",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        1720,
        -300
      ],
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "operation": "delete",
        "calendar": {
          "__rl": true,
          "value": "72fb857f192c8cca38c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "eventId": "={{ $json.properties['GCal ID'].rich_text[0].text.content }}",
        "options": {}
      },
      "id": "035613a9-9e24-4920-b09d-faa698fad02f",
      "name": "Delete event2",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        1720,
        -120
      ],
      "alwaysOutputData": false,
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "operation": "delete",
        "calendar": {
          "__rl": true,
          "value": "72fb857fe79192c8cca38c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "eventId": "={{ $json.properties['GCal ID'].rich_text[0].text.content }}",
        "options": {}
      },
      "id": "349034ba-f815-487f-b0d5-bbf77f372e57",
      "name": "Delete event1",
      "type": "n8n-nodes-base.googleCalendar",
      "typeVersion": 1,
      "position": [
        1720,
        160
      ],
      "alwaysOutputData": false,
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.properties.Data.date }}",
              "operation": "isNotEmpty"
            }
          ]
        }
      },
      "id": "45e49f4c-3c4d-4013-9a98-54334299b4b4",
      "name": "Does it have a date?1",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1140,
        640
      ]
    },
    {
      "parameters": {
        "conditions": {
          "string": [
            {
              "value1": "={{ $json.properties.Data.date.start }}",
              "operation": "contains",
              "value2": "T"
            }
          ]
        }
      },
      "id": "6cd5b8df-095a-4036-bfbd-ed9728bbb49f",
      "name": "Does it have a time?1",
      "type": "n8n-nodes-base.if",
      "typeVersion": 1,
      "position": [
        1360,
        580
      ]
    },
    {
      "parameters": {
        "pollTimes": {
          "item": [
            {
              "mode": "everyMinute"
            }
          ]
        },
        "calendarId": {
          "__rl": true,
          "value": "72fb857fe78a8c73b919eca@group.calendar.google.com",
          "mode": "list",
          "cachedResultName": "Notion Tasks"
        },
        "triggerOn": "eventCancelled",
        "options": {}
      },
      "id": "c3e10219-e042-439e-815c-82de4a22bbf0",
      "name": "Event cancelled (deleted)",
      "type": "n8n-nodes-base.googleCalendarTrigger",
      "typeVersion": 1,
      "position": [
        760,
        1440
      ],
      "credentials": {
        "googleCalendarOAuth2Api": {
          "id": "AtC7LU7bfV4kSHeC",
          "name": "Google Calendar"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "getAll",
        "databaseId": {
          "__rl": true,
          "value": "dad4835c-11440b13c475",
          "mode": "list",
          "cachedResultName": "Tasks",
          "cachedResultUrl": "https://www.notion.so/dad11440b13c475"
        },
        "returnAll": true,
        "filterType": "manual",
        "filters": {
          "conditions": [
            {
              "key": "GCal ID|rich_text",
              "condition": "equals",
              "richTextValue": "={{ $json.id }}"
            }
          ]
        },
        "options": {}
      },
      "id": "efd44e07-dc92-40b9-a005-4c469087420d",
      "name": "Find Task",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        980,
        1440
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "getAll",
        "databaseId": {
          "__rl": true,
          "value": "dad4835c-11440b13c475",
          "mode": "list",
          "cachedResultName": "Tasks",
          "cachedResultUrl": "https://www.notion.so/dad4835c1440b13c475"
        },
        "returnAll": true,
        "filterType": "manual",
        "filters": {
          "conditions": [
            {
              "key": "GCal ID|rich_text",
              "condition": "equals",
              "richTextValue": "={{ $json.id }}"
            }
          ]
        },
        "options": {}
      },
      "id": "7fab61d1-3320-447b-b35d-5e612b2a1bf6",
      "name": "Find Task1",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        980,
        1800
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "GCal ID|rich_text"
            },
            {
              "key": "Data|date"
            }
          ]
        },
        "options": {}
      },
      "id": "6a37d758-09b3-4402-b7f9-62d8dcf09bb2",
      "name": "Remove GCal ID and Date",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1200,
        1440
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    },
    {
      "parameters": {
        "resource": "databasePage",
        "operation": "update",
        "pageId": {
          "__rl": true,
          "value": "={{ $json.id }}",
          "mode": "id"
        },
        "propertiesUi": {
          "propertyValues": [
            {
              "key": "Data|date",
              "range": true,
              "dateStart": "={{ $('Event updated').item.json.start.dateTime }}",
              "dateEnd": "={{ $('Event updated').item.json.end.dateTime }}"
            }
          ]
        },
        "options": {}
      },
      "id": "2e1f8f7f-3cb7-4a23-9c12-04684caca203",
      "name": "Update day and time",
      "type": "n8n-nodes-base.notion",
      "typeVersion": 2,
      "position": [
        1200,
        1800
      ],
      "credentials": {
        "notionApi": {
          "id": "rbEZOwVdVyBUY4ph",
          "name": "Notion API"
        }
      }
    }
  ],
  "connections": {
    "Google Calendar1": {
      "main": [
        [
          {
            "node": "Add GCal ID",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Google Calendar2": {
      "main": [
        [
          {
            "node": "Add GCal ID2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Remove GCal ID": {
      "main": [
        [
          {
            "node": "Google Calendar2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Google Calendar": {
      "main": [
        [
          {
            "node": "Add GCal ID1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Notion": {
      "main": [
        [
          {
            "node": "Event exists in GCal?",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Event updated": {
      "main": [
        [
          {
            "node": "Find Task1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Event exists in GCal?": {
      "main": [
        [
          {
            "node": "Has it been deleted?",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Does it have a date?1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Has it been deleted?": {
      "main": [
        [
          {
            "node": "Delete event",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Does it have a date?",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Does it have a date?": {
      "main": [
        [
          {
            "node": "Does it have a time?",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Delete event1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Does it have a time?": {
      "main": [
        [
          {
            "node": "Update event",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Delete event2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Delete event": {
      "main": [
        [
          {
            "node": "Remove GCal ID1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Delete event2": {
      "main": [
        [
          {
            "node": "Remove GCal ID",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Delete event1": {
      "main": [
        [
          {
            "node": "Remove GCal ID2",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Does it have a date?1": {
      "main": [
        [
          {
            "node": "Does it have a time?1",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "No Operation, do nothing",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Does it have a time?1": {
      "main": [
        [
          {
            "node": "Google Calendar",
            "type": "main",
            "index": 0
          }
        ],
        [
          {
            "node": "Google Calendar1",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Event cancelled (deleted)": {
      "main": [
        [
          {
            "node": "Find Task",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Find Task": {
      "main": [
        [
          {
            "node": "Remove GCal ID and Date",
            "type": "main",
            "index": 0
          }
        ]
      ]
    },
    "Find Task1": {
      "main": [
        [
          {
            "node": "Update day and time",
            "type": "main",
            "index": 0
          }
        ]
      ]
    }
  },
  "pinData": {
    "Event updated": [
      {
        "kind": "calendar#event",
        "etag": "\"3404709771489000\"",
        "id": "sd0kv1vldv8ca8urg5m8ngehh4",
        "status": "confirmed",
        "htmlLink": "https://www.google.com/calendar/event?eid=c2Qwa3YxdmxkdjhjYTh1cmc1bThzhhOTdjOWFkMmQzNjFhMmI0MzM1MThkZjY1NDlhYzcxNDkxOTJjOGNjYTM4YzczYjkxOWVjYUBn",
        "created": "2023-12-12T04:17:58.000Z",
        "updated": "2023-12-12T04:24:52.742Z",
        "summary": "Vídeo que me vende como palestrante",
        "creator": {
          "email": "myemail@gmail.com"
        },
        "organizer": {
          "email": "72fb857351cca38c73b919eca@group.calendar.google.com",
          "displayName": "Notion Tasks",
          "self": true
        },
        "start": {
          "dateTime": "2023-12-13T10:00:00-03:00",
          "timeZone": "America/Sao_Paulo"
        },
        "end": {
          "dateTime": "2023-12-13T10:45:00-03:00",
          "timeZone": "America/Sao_Paulo"
        },
        "iCalUID": "sd0kv1vldvngehh4@google.com",
        "sequence": 1,
        "reminders": {
          "useDefault": false,
          "overrides": [
            {
              "method": "popup",
              "minutes": 60
            }
          ]
        },
        "eventType": "default"
      }
    ]
  }
}
`

**Comment by 5pecia1** [comment]
Looks very good!
I think most people will be fine using the code above.
I plan to develop the solution with a new n8n version. 
When developing a new version, it might be a good idea to use the code shared by @salomaoparkour.
Thanks for sharing!
